<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="categories-wp">
<?php // echo $this->getLayout()->createBlock('wordpress/sidebar_widget_categories')->setTemplate('wordpress/sidebar/widget/categories.phtml')->toHtml() ?>
</div>
<div class="blogpage-content">
<?php /* <div class="page-title blog-title <?php if (!$this->isFirstPage()): ?>not-<?php endif; ?>first-page<?php if ($this->isFirstPage() && $this->getTagLine()): ?> with-tagline<?php endif; ?>">
	<h1><?php echo $this->escapeHtml($this->getBlogTitle()) ?></h1>
</div> */ ?>
<?php /* if ($this->isFirstPage() && $this->getTagLine()): ?>
	<p class="blog-desc blog-tag-line"><?php echo $this->escapeHtml($this->getTagLine()) ?></p>
<?php endif; */ ?>
<div class="blog-home">
	<?php echo $this->getPostListHtml() ?>
</div>
</div>
