<?php
session_start();$OptionCountry = $this->getCountry();
$_showSearch = Mage::getStoreConfig('storelocator/general/default_location');
?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <title>Pazzey's Store Locator</title>
	<?php $height = '500'; 
		  $height = $height - 200; ?>
    <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>

	<script src="code.jquery.com/jquery-1.11.0.min.js"></script>
	<script type="text/javascript" src="http://clients.osworlds.com/w_lgn/wp-content/themes/lgn/js/jSelect.js"></script>
	<?php /*
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/ultimo/default/md/storelocator/jquery-1.11.0.min.js' ?>"></script> 
	<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/ultimo/default/md/storelocator/jSelect.js' ?>"></script>
	*/ ?>
	
	<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function( $ ) {
		// jQuery(function(){
			// jQuery("select#city").jSelect({listwidth:'150px',editable:true});
		// })
		jQuery('#content_progress').ajaxStart(function(){
               jQuery(this).html('<img src="http://www.egeraspa.com/wp-content/themes/crn/framework/images/icons/loading.gif" />');
               jQuery(this).fadeIn();
            });
            jQuery('#content_progress').ajaxComplete(function(){
               jQuery(this).fadeOut();
            });
	})
	</script>	
    <script type="text/javascript">
    //<![CDATA[
    var map;
    var markers = [];
	var side_bar_html = "";
    var infoWindow;
    var locationSelect;

    function load() {
      map = new google.maps.Map(document.getElementById("map"), {
       center: new google.maps.LatLng(41.87194, 12.567379999999957),
        zoom: 5,
			
        mapTypeId: 'roadmap',
        mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
      });
      infoWindow = new google.maps.InfoWindow();
      locationSelect = document.getElementById("locationSelect");
      locationSelect.onchange = function() {
        var markerNum = locationSelect.options[locationSelect.selectedIndex].value;
        if (markerNum != "none"){
          google.maps.event.trigger(markers[markerNum], 'click');
        }
      };
	  
	  var styles = [
	  {
    featureType: "all",
    stylers: [
	{ hue: "#ddd0bd" },
      { saturation: -30 }
    ]
  },
  {
    stylers: [
      { hue: "#ddd0bd" },
      { saturation: -55 }
    ]
  },{
    featureType: "road",
    elementType: "geometry",
    stylers: [
      { lightness: 0 },
      { visibility: "simplified" }

    ]
  },{
    featureType: "road",
    elementType: "labels",
    stylers: [
      { visibility: "off" }
    ]
  }
];

map.setOptions({styles: styles});

   }

   function searchLocations(tm) {
     var address = document.getElementById("addressInput").value;
     var geocoder = new google.maps.Geocoder();
     geocoder.geocode({address: address}, function(results, status) {
		if (tm == "3") { 
			searchLocationsNear('1234',tm);
		} else {
       if (status == google.maps.GeocoderStatus.OK) {
	   
	   // jQuery.ajax({
			 // type: "POST",
			   // url:"<?php echo $this->getUrl('storelocator/location/getfinter');?>",
			   // data: 'lat=' + 0 + '&lng=' + 0 + '&country=0',
			   // success:function(data){
					// jQuery('#selectbox').html(data);
			   // }
			  // });
        searchLocationsNear(results[0].geometry.location,tm);
		jQuery('#side_bar').empty();
		jQuery('#city').val('');
		jQuery('#back').hide();
		jQuery('#content').hide();
       } else {
         var search='<?php echo Mage::getSingleton('core/session')->getSearchvalue() ?>';
         jQuery('#addressInput').val(search);
		 jQuery('#result_search').hide();
       }
       }	   
     });
	 jQuery('#result_search').hide();
   }   
  
   function fillterLocations(tm,tm1,tm2,tm3) {
     var address = document.getElementById("addressInput").value;
	 // var country = document.getElementById("city").value;
     var geocoder = new google.maps.Geocoder();
     geocoder.geocode({address: address}, function(results, status) {
		if (tm == "3") {
			fillterLocationsNear('1234',tm,tm1,tm2,tm3);
		} else {
       if (status == google.maps.GeocoderStatus.OK) {
		// jQuery.ajax({
			 // type: "POST",
			   // url:"<?php echo $this->getUrl('storelocator/location/getfinter');?>",
			   // data: 'lat=' + results[0].geometry.location.lat() + '&lng=' +results[0].geometry.location.lng()+ '&country=' + country,
			   // success:function(data){
					// jQuery('#selectbox').html(data);
			   // }
			  // });
        fillterLocationsNear(results[0].geometry.location,tm,tm1,tm2,tm3);
       } else {
         var search='<?php echo Mage::getSingleton('core/session')->getSearchvalue() ?>';
         jQuery('#addressInput').val(search);
		 jQuery('#result_search').hide();
       }
       }	   
     });
	 jQuery('#result_search').hide();
   }   
  

   function searchLocationsNear(center,tm) {
     clearLocations(); 	 
     var radius = document.getElementById('radiusSelect').value;
	 var country = document.getElementById('addressInput').value;
	 // var city2 = document.getElementById('city').value;
	 var sort = document.getElementById('sort').value;	 var page='<?php echo $_GET["page"] ?>';	 if(page=='verona'){		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort + '&country=' + country +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius + '&page=' + page;	 }	 else
	 if (tm == "4") {
		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&lat=' + center.lat() + '&lng=' +center.lng() + '&radius=' + radius;
	 }else
	 if (tm == "3") {
	 } else {
		 if (tm == '2'){
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort + '&country=' + country +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;		
		 } else {
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius ;
		 }
	 }
     downloadUrl(searchUrl, function(data) {
       var xml = parseXml(data);
       var markerNodes = xml.documentElement.getElementsByTagName("marker");
       var bounds = new google.maps.LatLngBounds();
       for (var i = 0; i < markerNodes.length; i++) {
         var name = markerNodes[i].getAttribute("name");
         var email = markerNodes[i].getAttribute("email");
         var phone = markerNodes[i].getAttribute("phone");
         var address = markerNodes[i].getAttribute("address");	 
         var distance = parseFloat(markerNodes[i].getAttribute("distance"));
		 var moreinfo = markerNodes[i].getAttribute("moreinfo");
		 var flagship = markerNodes[i].getAttribute("notes");
		 var image1 = markerNodes[i].getAttribute("image1");
		 var image2 = markerNodes[i].getAttribute("image2");
		 var image3 = markerNodes[i].getAttribute("image3");
		 var image4 = markerNodes[i].getAttribute("image4");
         var latlng = new google.maps.LatLng(
              parseFloat(markerNodes[i].getAttribute("lat")),
              parseFloat(markerNodes[i].getAttribute("lng")));
		
		var mydistance = markerNodes[i].getAttribute("mydistance");
		var icon=i+1;
		

         createOption(name, distance, i);
         createMarker(latlng, name, address, moreinfo,email,phone,mydistance,icon,image1,image2,image3,image4,flagship,page);
         bounds.extend(latlng);
       }
       map.fitBounds(bounds);
	    map.setZoom(5);
	   if (side_bar_html != "") {
	   document.getElementById("side_bar").innerHTML = '<div class="heading clearfix animated unselectable hidden" style=" ">Stores<div class="hide"><div class="icon black" style=" "></div><div class="icon grey" style="display:none"></div></div></div><ul class="paging">' + side_bar_html + '</ul>';}
      });
    }
	
	
	function fillterLocationsNear(center,tm,tm1,tm2,tm3) {
     clearLocations();		  
     var radius = document.getElementById('radiusSelect').value;
	 var country = document.getElementById('addressInput').value;
	 // var city2 = document.getElementById('city').value;
	 var sort = document.getElementById('sort').value;
	 if (tm == "4") {
		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&tm1=' + tm1 +'&tm2=' + tm2 +'&tm3=' + tm3 +'&lat=' + center.lat() + '&lng=' +center.lng() + '&radius=' + radius;
	 }else
	 if (tm == "3") {
		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&lat=21.5433333&lng=39.17277779999995&radius=16';
	 } else {
		 if (tm == '2'){
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&tm1=' + tm1 +'&tm2=' + tm2 +'&tm3=' + tm3 + '&country=' + country +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;		
		 } else {
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&tm1=' + tm1 +'&tm2=' + tm2 +'&tm3=' + tm3 +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;
		 }
	 }
     downloadUrl(searchUrl, function(data) {
       var xml = parseXml(data);
       var markerNodes = xml.documentElement.getElementsByTagName("marker");
       var bounds = new google.maps.LatLngBounds();
       for (var i = 0; i < markerNodes.length; i++) {
         var name = markerNodes[i].getAttribute("name");
         var email = markerNodes[i].getAttribute("email");
         var phone = markerNodes[i].getAttribute("phone");
         var address = markerNodes[i].getAttribute("address");	 
         var distance = parseFloat(markerNodes[i].getAttribute("distance"));
		 var moreinfo = markerNodes[i].getAttribute("moreinfo");
		 var flagship = markerNodes[i].getAttribute("notes");
		 var image1 = markerNodes[i].getAttribute("image1");
		 var image2 = markerNodes[i].getAttribute("image2");
		 var image3 = markerNodes[i].getAttribute("image3");
		 var image4 = markerNodes[i].getAttribute("image4");
         var latlng = new google.maps.LatLng(
              parseFloat(markerNodes[i].getAttribute("lat")),
              parseFloat(markerNodes[i].getAttribute("lng")));
		
		var mydistance = markerNodes[i].getAttribute("mydistance");
		var icon=i+1;
		

         createOption(name, distance, i);		 var page='1';
         createMarker(latlng, name, address, moreinfo,email,phone,mydistance,icon,image1,image2,image3,image4,flagship,page);
         bounds.extend(latlng);
       }
       map.fitBounds(bounds);
	   if (side_bar_html == "") {
	   document.getElementById("side_bar").innerHTML = '<strong>No Matches Found</strong>';}
	   else {
	   document.getElementById("side_bar").innerHTML = '<div class="heading clearfix animated unselectable hidden" style=" ">Stores<div class="hide"><div class="icon black" style=" "></div><div class="icon grey" style="display:none"></div></div></div><ul class="content">' + side_bar_html + '</ul>';jQuery('.content-map').pajinate();}
      });
    }
  
    function createMarker(latlng, name, address, moreinfo,email,phone,mydistance,icon,image1,image2,image3,image4,flagship,page) {
	if(address !='')
	{
      // var html = "<b>" + name + "</b> <br/>" + address + "<br/>" + moreinfo;
       var html = '<div class="map-detail">';
	html = html + '<div class="grid-full name-map"><div class="grid12-3"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image1+'" /></div><div class="grid12-9"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image2+'" /></div><div class="text-address">flagshipstore<br/>'+ name +'</div></div>';
	html = html + '<div class="clear"></div><div class="map-detail-content"><div class="grid-full">';
	html = html + '<div class="grid12-4 address-map"><div>'+ name +'<div>' + address + '</div><div>'+'T: ' + phone + '</div></div><div class="right"></div></div>';
	html = html + '<div class="grid12-4"><p>'+moreinfo+'</p></div>';
	html = html + '<div class="grid12-4"><p>'+moreinfo+'</p></div>';
	html = html + '</div><div class="clear"></div></div>';
	html = html + '<div class="grid-full buy-map"><div class="grid12-6"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image3+'" /></div><div class="grid12-6"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image4+'" /></div></div>';
	  var cleanaddy = address.replace(/<\/?[^>]+(>|$)/g, "");
	  // html +='<form action="http://maps.google.com/maps" method="get"" target="_blank">'+
           // '<INPUT value="Get Directions" TYPE="SUBMIT">' +
           // '<input type="hidden" name="daddr" value="' + cleanaddy +
           // '"/>';
	  var shadow = new google.maps.MarkerImage('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/ultimo/default/md/storelocator/bg_br.png' ?>', new google.maps.Size(0, 0) );	   
	  
      var marker = new google.maps.Marker({
        map: map,
		shadow: shadow,
        position: latlng
      });		if(page !='1'){			jQuery('#detail').show();			jQuery('#detail').html(html);			jQuery('#content').hide();			jQuery('#search-left').hide();			jQuery('#side_bar').hide();		}
      google.maps.event.addListener(marker, 'click', function() {
	  	if(flagship != 2)
	  {
		jQuery('#detail').show();
		jQuery('#detail').html(html);
		
		jQuery('#content').hide();
		jQuery('#search-left').hide();
		jQuery('#side_bar').hide();
		setAllMap(null);
		marker.setMap(map);
		}
		else{
			jQuery("html, body").animate({scrollTop: 250}, 1000);
			jQuery('#content').show();
			jQuery('#side_bar').show();
			jQuery('#search-left').show();
			jQuery('#detail').empty();
			jQuery('#back').show();
		}
      });
	  setAllMap(map);
      markers.push(marker);
	  
	  var image='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=9c0d10,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	  var image2='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=333333,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	  // if(icon>25){
	  // var image='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=333333,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	  // var image2='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=CC0000,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	  // }
	  marker.setIcon(image);
	  if(flagship != 2)
	  {
		side_bar_html += '<li class="store_item"><div class="whiteLine"></div><div class="marker"><div class="list-marker performance" style="background: url('+image2+') no-repeat" ></div><p><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')">'+ mydistance +' km'+'</a></p></div><div class="text"><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')"><h2>' + name + '</h2></a><p><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')">'+ address +'</a></p><p><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')">'+ email +'</a></p><div class="tagList"></div><div class="dottedLine"></div></div></li>';
		} else {
		side_bar_html += '<li class="store_item no-flagship-color"><div class="whiteLine"></div><div class="marker"><div class="list-marker performance" style="background: url('+image2+') no-repeat" ></div><p><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')">'+ mydistance +' Km'+'</a></p></div><div class="text"><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')"><h2>' + name + '</h2></a><p><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')">'+ address +'</a></p><p><a href="javascript:myclick(' + (markers.length-1)+','+flagship + ')">'+ email +'</a></p><div class="tagList"></div><div class="dottedLine"></div></div></li>';
		}
		jQuery('.content-map').pajinate();
	}
    }
function setAllMap(map) {
   for (var i = 0; i < markers.length; i++) {
      markers[i].setMap(map);
   }
}
function myclick(i,flagship) {
	if(flagship != 2){
	  google.maps.event.trigger(markers[i], "click");
	  jQuery('#content').hide();
	  jQuery('#side_bar').hide();
	  jQuery('#search-left').hide();
	  jQuery('#back').hide();
	}
	else{
		jQuery("html, body").animate({scrollTop: 200}, 1000);
	}
}

    function createOption(name, distance, num) {
      var option = document.createElement("option");
      option.value = num;
      option.innerHTML = name + "(" + distance.toFixed(1) + ")";
      locationSelect.appendChild(option);
    }

    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;

      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };

      request.open('GET', url, true);
      request.send(null);
    }

    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }

    function doNothing() {}

    //Nothing here>
	function changetab(tm,tm2){
		jQuery('.tabstyle').attr('style','');
		jQuery('#' + tm2).attr('style','background: #fff;border-right: 1px solid #E5E5E5;border-left: 1px solid #E5E5E5');
		jQuery('#tab1content').addClass('hidencontenttab');
		jQuery('#tab2content').addClass('hidencontenttab');
		jQuery('#' + tm).removeClass('hidencontenttab');
		jQuery('#' + tm).show();
	}
	function changecity(tm){
		if (jQuery('#city').val() == "0"){
			searchLocations(3);
		} else {
			searchLocations(tm);
			
			// var country = document.getElementById('city').value;
			 // jQuery.ajax({
			 // type: "POST",
			   // url:"<?php echo $this->getUrl('storelocator/location/getfinter');?>",
			   // data: 'country=' + country,
			   // success:function(data){
					// jQuery('#finter').html(data);
			   // }
			  // });
		}	
	}
			
		

	
	
	 function changevalue(e)
	 {
		jQuery('#addressInput').val(e);
		jQuery('#result_search').hide();
		 fillterLocations(2,1,2,3);
	 }
	 function search()
	 {	
		fillterLocations(2,1,2,3);
		jQuery('#content').show();
		jQuery('#side_bar').show();
		jQuery('#back').show();
		jQuery('#detail').hide();
		jQuery('#city').show();
	 }
	 jQuery( document ).ready(function( $ ) {
		jQuery('#addressInput').keyup(function(e) {
			if(e.keyCode == 13) {
				fillterLocations(2,1,2,3);
				jQuery('#content').show();
				jQuery('#side_bar').show();
				jQuery('#back').show();
				jQuery('#detail').hide();
				jQuery('#city').show();
			}
		});
	})
	 
	 function changesort()
	 {
		 fillterLocations(2,1,2,3);
	 }
	
	function backurl()
	 {
		parent.history.back();
        return false;
	 }

	
	function clearLocations() {
     // infoWindow.close();
     for (var i = 0; i < markers.length; i++) {
       markers[i].setMap(null);
     }
     markers.length = 0;
	side_bar_html = "";
   }
  </script>
</head>
<body style="margin:0px; padding:0px;" onLoad="load()" class="storelocator">
<script type="text/javascript">
(function($){
/*******************************************************************************************/    
// jquery.pajinate.js - version 0.4
// A jQuery plugin for paginating through any number of DOM elements
// 
// Copyright (c) 2010, Wes Nolte (http://wesnolte.com)
// Licensed under the MIT License (MIT-LICENSE.txt)
// http://www.opensource.org/licenses/mit-license.php
// Created: 2010-04-16 | Updated: 2010-04-26
//
/*******************************************************************************************/

    $.fn.pajinate = function(options){
        // Set some state information
        var current_page = 'current_page';
		var items_per_page = 'items_per_page';
		
		var meta;
	
		// Setup default option values
		var defaults = {
			item_container_id : '.content',
			items_per_page : 20,			
			nav_panel_id : '.page_navigation',
			nav_info_id : '.info_text',
			num_page_links_to_display : 20,			
			start_page : 0,
			wrap_around : false,
			nav_label_first : 'First',
			nav_label_prev : 'Prev',
			nav_label_next : 'Next',
			nav_label_last : 'Last',
			nav_order : ["first", "prev", "num", "next", "last"],
			nav_label_info : 'Showing {0}-{1} of {2} results',
            show_first_last: true,
            abort_on_small_lists: false,
            jquery_ui: false,
            jquery_ui_active: "ui-state-highlight",
            jquery_ui_default: "ui-state-default",
            jquery_ui_disabled: "ui-state-disabled"
		};
		var options = $.extend(defaults,options);
		var $item_container;
		var $page_container;
		var $items;
		var $nav_panels;
        var total_page_no_links;
        var jquery_ui_default_class = options.jquery_ui ? options.jquery_ui_default : '';
        var jquery_ui_active_class = options.jquery_ui ? options.jquery_ui_active : '';
        var jquery_ui_disabled_class = options.jquery_ui ? options.jquery_ui_disabled : '';
	

		return this.each(function(){
			$page_container = $(this);
			$item_container = $(this).find(options.item_container_id);
			$items = $page_container.find(options.item_container_id).children();
			
			if (options.abort_on_small_lists && options.items_per_page >= $items.size())
                return $page_container;
			meta = $page_container;
			
			// Initialize meta data
			meta.data(current_page,0);
			meta.data(items_per_page, options.items_per_page);
					
			// Get the total number of items
			var total_items = $item_container.children().size();
			
			// Calculate the number of pages needed
			var number_of_pages = Math.ceil(total_items/options.items_per_page);
			
			// Construct the nav bar
			var more = '<span class="ellipse more">...</span>';
			var less = '<span class="ellipse less">...</span>';
            var first = !options.show_first_last ? '' : '<a class="first_link '+ jquery_ui_default_class +'" href="">'+ options.nav_label_first +'</a>';
            var last = !options.show_first_last ? '' : '<a class="last_link '+ jquery_ui_default_class +'" href="">'+ options.nav_label_last +'</a>';
			
			var navigation_html = "";
			for(var i = 0; i < options.nav_order.length; i++) {
				switch (options.nav_order[i]) {
				case "first":
					navigation_html += first;
					break;
				case "last":
					navigation_html += last;
					break;
				case "next":
					navigation_html += '<a class="next_link '+ jquery_ui_default_class +'" href="">'+ options.nav_label_next +'</a>';
					break;
				case "prev":
					navigation_html += '<a class="previous_link '+ jquery_ui_default_class +'" href="">'+ options.nav_label_prev +'</a>';
					break;
				case "num":
					navigation_html += less;
					var current_link = 0;
					while(number_of_pages > current_link){
						navigation_html += '<a class="page_link '+ jquery_ui_default_class +'" href="" longdesc="' + current_link +'">'+ (current_link + 1) +'</a>';
						current_link++;
					}
					navigation_html += more;
					break;
				default:
					break;
				}
					
			}
			
			// And add it to the appropriate area of the DOM	
			$nav_panels = $page_container.find(options.nav_panel_id);			
			$nav_panels.html(navigation_html).each(function(){
			
				$(this).find('.page_link:first').addClass('first');
				$(this).find('.page_link:last').addClass('last');
				
			});
			
			// Hide the more/less indicators
			$nav_panels.children('.ellipse').hide();
			
			// Set the active page link styling
			$nav_panels.find('.previous_link').next().next().addClass('active_page '+ jquery_ui_active_class);
			
			/* Setup Page Display */
			// And hide all pages
			$items.hide();
			// Show the first page			
			$items.slice(0, meta.data(items_per_page)).show();

			/* Setup Nav Menu Display */
			// Page number slices
			
			total_page_no_links = $page_container.children(options.nav_panel_id+':first').children('.page_link').size();
			options.num_page_links_to_display = Math.min(options.num_page_links_to_display,total_page_no_links);

			$nav_panels.children('.page_link').hide(); // Hide all the page links
			
			// And only show the number we should be seeing
			$nav_panels.each(function(){
				$(this).children('.page_link').slice(0, options.num_page_links_to_display).show();			
			});
			
			/* Bind the actions to their respective links */
			 
			// Event handler for 'First' link
			$page_container.find('.first_link').click(function(e){
				e.preventDefault();
				
				movePageNumbersRight($(this),0);
				gotopage(0);				
			});			
			
			// Event handler for 'Last' link
			$page_container.find('.last_link').click(function(e){
				e.preventDefault();
				var lastPage = total_page_no_links - 1;
				movePageNumbersLeft($(this),lastPage);
				gotopage(lastPage);				
			});			
			
			// Event handler for 'Prev' link
			$page_container.find('.previous_link').click(function(e){
				e.preventDefault();
				showPrevPage($(this));
			});
			
			
			// Event handler for 'Next' link
			$page_container.find('.next_link').click(function(e){
				e.preventDefault();				
				showNextPage($(this));
			});
			
			// Event handler for each 'Page' link
			$page_container.find('.page_link').click(function(e){
				e.preventDefault();
				gotopage($(this).attr('longdesc'));
			});			
			
			// Goto the required page
			gotopage(parseInt(options.start_page));
			toggleMoreLess();
            if(!options.wrap_around)
			    tagNextPrev();
		});
		
		function showPrevPage(e){
			new_page = parseInt(meta.data(current_page)) - 1;						
			
			// Check that we aren't on a boundary link
			if($(e).siblings('.active_page').prev('.page_link').length==true){
				movePageNumbersRight(e,new_page);
				gotopage(new_page);
			}else if(options.wrap_around){
                gotopage(total_page_no_links-1);   
			}
				
		};
			
		function showNextPage(e){
			new_page = parseInt(meta.data(current_page)) + 1;
			
			// Check that we aren't on a boundary link
			if($(e).siblings('.active_page').next('.page_link').length==true){		
				movePageNumbersLeft(e,new_page);
				gotopage(new_page);
			} else if (options.wrap_around) {
				gotopage(0);
			}
				
		};
			
		function gotopage(page_num){
			
			var ipp = parseInt(meta.data(items_per_page));
			
			var isLastPage = false;
			
			// Find the start of the next slice
			start_from = page_num * ipp;
			
			// Find the end of the next slice
			end_on = start_from + ipp;
			// Hide the current page	
			var items = $items.hide().slice(start_from, end_on);
			
			items.show();
			
			// Reassign the active class
			$page_container.find(options.nav_panel_id).children('.page_link[longdesc=' + page_num +']').addClass('active_page '+ jquery_ui_active_class)
													 .siblings('.active_page')
													 .removeClass('active_page ' + jquery_ui_active_class);										 
			
			// Set the current page meta data							
			meta.data(current_page,page_num);
			
			$page_container.find(options.nav_info_id).html(options.nav_label_info.replace("{0}",start_from+1).
					replace("{1}",start_from + items.length).replace("{2}",$items.length));
			
			// Hide the more and/or less indicators
			toggleMoreLess();
			
			// Add a class to the next or prev links if there are no more pages next or previous to the active page
			tagNextPrev();
		};	
		
		// Methods to shift the diplayed index of page numbers to the left or right
		function movePageNumbersLeft(e, new_p){
			var new_page = new_p;
			
			var $current_active_link = $(e).siblings('.active_page');
		
			if($current_active_link.siblings('.page_link[longdesc=' + new_page +']').css('display') == 'none'){
				
				$nav_panels.each(function(){
							$(this).children('.page_link')
								.hide() // Hide all the page links
								.slice(parseInt(new_page - options.num_page_links_to_display + 1) , new_page + 1)
								.show();		
							});
			}
			
		} 
		
		function movePageNumbersRight(e, new_p){
			var new_page = new_p;
			
			var $current_active_link = $(e).siblings('.active_page');
			
			if($current_active_link.siblings('.page_link[longdesc=' + new_page +']').css('display') == 'none'){
												
				$nav_panels.each(function(){
							$(this).children('.page_link')
								.hide() // Hide all the page links
								.slice( new_page , new_page + parseInt(options.num_page_links_to_display))
								.show();
							});
			}
		}
		
		// Show or remove the ellipses that indicate that more page numbers exist in the page index than are currently shown
		function toggleMoreLess(){
													 
			if(!$nav_panels.children('.page_link:visible').hasClass('last')){					
				$nav_panels.children('.more').show();
			}else {
				$nav_panels.children('.more').hide();
			}
			
			if(!$nav_panels.children('.page_link:visible').hasClass('first')){
				$nav_panels.children('.less').show();
			}else {
				$nav_panels.children('.less').hide();
			}			
		}
		
        /* Add the style class ".no_more" to the first/prev and last/next links to allow custom styling */
    	function tagNextPrev() {
			if($nav_panels.children('.last').hasClass('active_page')){
				$nav_panels.children('.next_link').add('.last_link').addClass('no_more ' + jquery_ui_disabled_class);
			} else {
				$nav_panels.children('.next_link').add('.last_link').removeClass('no_more ' + jquery_ui_disabled_class);
			}
			
			if($nav_panels.children('.first').hasClass('active_page')){
				$nav_panels.children('.previous_link').add('.first_link').addClass('no_more ' + jquery_ui_disabled_class);
			} else {
				$nav_panels.children('.previous_link').add('.first_link').removeClass('no_more ' + jquery_ui_disabled_class);
			}
		}
		
	};
	
})(jQuery);
</script>

  <div class="storewrap">
			<div id="detail"></div>	
			<div class="clear"></div>
			<table border="0" bordercolor="" style="position: relative;z-index: 1;" width="100%" cellpadding="0" cellspacing="0">
			<tr>								
				
				<td class="map">		  
					<div id="map" ></div>					
				</td>
			</tr>
		</table>
			
			<div id="headerContainer">
				<div id="search-left">
					<div class="page-title">
						<h1><?php echo $this->__('Select city') ?></h1>
					</div>
					<div class="head-left">
						<?php /* <div class="gmnoprint title unselectable" id="topTitle">
						
						</div> */ ?>
						<div id="search-left" class="search-left">
							<div class="test-search">
								<?php if (Mage::getSingleton('core/session')->getSearchvalue()!= "") { ?>
								<input type="text" value="<?php echo Mage::getSingleton('core/session')->getSearchvalue() ?>" id="addressInput"  size="30" />
								<?php } else { ?>
								<input type="text" id="addressInput"  size="30" />
								
								<?php } ?>
								<div class="searchButton unselectable">
									<div class="normal"></div>
									<div class="highlighted btn-search" onClick="search()" style="display: block;">Search</div>
								</div>
								
								<div id="content_progress" style="float:left"></div>
								<div class="clear"></div>
							</div>
							
						</div>
					</div>
				<div>
				<div class="collect-map">
					<a href="#"><div id="back" onClick="searchLocations(2)"   ><h4>back</h4></div></a>
				</div>
				<div class="head-right ">
				
					<div class="searchform hidden" >						
						<div id="selectbox">
							<!--select id="city" onchange="changecity(1)">						
									<option  value=""></option>
							</select-->
						</div>						
					</div>
					
					<select id="radiusSelect" style="display:none">
					  <option value="16" selected>25 miles</option>
					  <option value="16">100 miles</option>
					  <option value="16">200 miles</option>
					</select>
					
				</div>	
				<div class="clear"></div>
			<div id="finter" class="search-bottom hidden" style="padding-top:20px;" >				
			</div>
			<div class="clear"></div>
			
			<div class="search-bottom hidden" style=" width:150px;padding:10px;">
				<div><strong>Search Results</strong></div>
				<div><select id="sort" style="width:130px" onChange="changesort()">
						<option  value="" selected="selected">sort by</option>
						<option  value="distance_asc" >Distance (ascending ↑)</option>
						<option  value="distance_desc" >Distance (descending ↓)</option>
						<option  value="name_asc" >Name (ascending ↑)</option>
						<option  value="name_desc" >Name (descending ↓)</option>
					</select>
				</div>
			</div>

			<div class="clear"></div>
			</div>			
			<div style="display:none"><select id="locationSelect" style="width:100%;visibility:hidden"></select></div>
			
			<div id="content">
				<div class="content-map">
					<div id="side_bar"></div>
					<div class="page_navigation"></div>	
					<div class="info_text"></div>
				</div>
				
			</div>	
		
	</div>
	</div><script> searchLocations(2);
</script>
	<style>
		.page_navigation , .alt_page_navigation{
			padding-bottom: 10px;
		}

		.page_navigation a, .alt_page_navigation a{
			padding:3px 5px;
			margin:2px;
			color:white;
			text-decoration:none;
			float: left;
			font-family: Tahoma;
			font-size: 12px;
			background-color:#DB5C04;
		}
		.active_page{
			background-color:white !important;
			color:black !important;
		}
		.map img {
			max-width: none!important;
		}
		.gm-style-iw { top:0 !important;left: 0 !important;width: 410px }
		.tabstyle { color: #999999;cursor: pointer;float: left;font-family: CustomAdiHausPSBold,arial,helvetica,sans-serif;font-size: 12px;font-weight: normal;line-height: 100%;padding: 22px 20px 15px;text-align: left;text-decoration: none;text-transform: uppercase;vertical-align: middle;}
		.content_info { height: 105px;overflow: auto; }
		.gm-style > div > div > div > div > div,.gm-style > div > div > div > div > div > div > div { width: 410px !important;border: none !important}
		.gm-style-iw, .gm-style-iw > div {     overflow-x: hidden !important;overflow-y: auto !important;}
		.hidencontenttab { display:none !important}
		#city {height: 50px;padding: 16px 10px;width: 106px;}
		.tabcontent p { font-size: 14px; margin-bottom: 1px; margin-top: 0 !important; text-transform: none; }
		.storewrap img {max-width: none;}
	</style>

</body>
</html>