<?php
session_start();$OptionCountry = $this->getCountry();
$_showSearch = Mage::getStoreConfig('storelocator/general/default_location');
?>
    <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
	
	<script type="text/javascript">
	jQuery.noConflict();
	jQuery(document).ready(function( $ ) {
		jQuery('#content_progress').ajaxStart(function(){
               jQuery(this).html('<img src="http://www.egeraspa.com/wp-content/themes/crn/framework/images/icons/loading.gif" />');
               jQuery(this).fadeIn();
            });
            jQuery('#content_progress').ajaxComplete(function(){
               jQuery(this).fadeOut();
            });
	})
	</script>	
    
    <script type="text/javascript">
    //<![CDATA[
    var map;
    var markers = [];
	var side_bar_html = "";
    var infoWindow;
    var locationSelect;
    function load() {
      map = new google.maps.Map(document.getElementById("map"), {
       center: new google.maps.LatLng(41.87194, 12.567379999999957),
        zoom: 5,
			
        mapTypeId: 'roadmap',
        mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU}
      });
      infoWindow = new google.maps.InfoWindow();
      locationSelect = document.getElementById("locationSelect");
      locationSelect.onchange = function() {
        var markerNum = locationSelect.options[locationSelect.selectedIndex].value;
        if (markerNum != "none"){
          google.maps.event.trigger(markers[markerNum], 'click');
        }
      };
	  
	  var styles = [
	  {
    featureType: "all",
    stylers: [
	{ },
      {/*  saturation: -30  */}
    ]
  },
  {
    stylers: [
      { },
      { /* saturation: -55 */ }
    ]
  },{
    featureType: "road",
    elementType: "geometry",
    stylers: [
      { lightness: 0 },
      { /* visibility: "simplified"  */}
    ]
  },{
    featureType: "road",
    elementType: "labels",
    stylers: [
      { visibility: "off" }
    ]
  }
];
map.setOptions({styles: styles});
   }
   function searchLocations(tm) {
     var address = document.getElementById("addressInput").value;
     var geocoder = new google.maps.Geocoder();
     geocoder.geocode({address: address}, function(results, status) {
		if (tm == "3") { 
			searchLocationsNear('1234',tm);
		} else {
       if (status == google.maps.GeocoderStatus.OK) {
        searchLocationsNear(results[0].geometry.location,tm);
		jQuery('#side_bar').empty();
		jQuery('#city').val('');
		jQuery('#back').hide();
		jQuery('#content').hide();
       } else {
         var search='<?php echo Mage::getSingleton('core/session')->getSearchvalue() ?>';
         jQuery('#addressInput').val(search);
		 jQuery('#result_search').hide();
       }
       }	   
     });
	 jQuery('#result_search').hide();
   }   
  
   function fillterLocations(tm,tm1,tm2,tm3) {
     var address = document.getElementById("addressInput").value;
	
     var geocoder = new google.maps.Geocoder();
     geocoder.geocode({address: address}, function(results, status) {
		if (tm == "3") {
			fillterLocationsNear('1234',tm,tm1,tm2,tm3);
		} else {
       if (status == google.maps.GeocoderStatus.OK) {
        fillterLocationsNear(results[0].geometry.location,tm,tm1,tm2,tm3);
       } else {
         var search='<?php echo Mage::getSingleton('core/session')->getSearchvalue() ?>';
         jQuery('#addressInput').val(search);
		 jQuery('#result_search').hide();
       }
       }	   
     });
	 jQuery('#result_search').hide();
	
   }   
  
   function searchLocationsNear(center,tm) {
     clearLocations(); 	 
     var radius = "";
	 var country = document.getElementById('addressInput').value;
	 // var city2 = document.getElementById('city').value;
	 var sort = "";	 var page='<?php echo $_GET["page"] ?>';	 if(page=='verona'){		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort + '&country=' + country +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius + '&page=' + page;	 }	 else
	 if (tm == "4") {
		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&lat=' + center.lat() + '&lng=' +center.lng() + '&radius=' + radius;
	 }else
	 if (tm == "3") {
	 } else {
		 if (tm == '2'){
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort + '&country=' + country +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;		
		 } else {
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius ;
		 }
	 }
     downloadUrl(searchUrl, function(data) {
       var xml = parseXml(data);
       var markerNodes = xml.documentElement.getElementsByTagName("marker");
       var bounds = new google.maps.LatLngBounds();
       for (var i = 0; i < markerNodes.length; i++) {
         var name = markerNodes[i].getAttribute("name");
         var email = markerNodes[i].getAttribute("email");
         var phone = markerNodes[i].getAttribute("phone");
         var address = markerNodes[i].getAttribute("address");	 
         var distance = parseFloat(markerNodes[i].getAttribute("distance"));
		 var moreinfo = markerNodes[i].getAttribute("moreinfo");
		 var flagship = markerNodes[i].getAttribute("notes");
		 var image1 = markerNodes[i].getAttribute("image1");
		 var image2 = markerNodes[i].getAttribute("image2");
		 var image3 = markerNodes[i].getAttribute("image3");
		 var image4 = markerNodes[i].getAttribute("image4");
         var latlng = new google.maps.LatLng(
              parseFloat(markerNodes[i].getAttribute("lat")),
              parseFloat(markerNodes[i].getAttribute("lng")));
		
		var mydistance = markerNodes[i].getAttribute("mydistance");
		var icon=i+1;
		
         createOption(name, distance, i);
         createMarker(latlng, name, address, moreinfo,email,phone,mydistance,icon,image1,image2,image3,image4,flagship,page);
         bounds.extend(latlng);
       }
       map.fitBounds(bounds);
	    map.setZoom(5);
	   if (side_bar_html != "") {
	   document.getElementById("side_bar").innerHTML = '<div class="heading clearfix animated unselectable hidden" style=" ">Stores<div class="hide"><div class="icon black" style=" "></div><div class="icon grey" style="display:none"></div></div></div><ul class="paging">' + side_bar_html + '</ul>';}
      });
    }
	
	
	function fillterLocationsNear(center,tm,tm1,tm2,tm3) {
     clearLocations();		  
     var radius = "";
	 var country = document.getElementById('addressInput').value;
	 // var city2 = document.getElementById('city').value;
	 var sort = "";
	 if (tm == "4") {
		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&tm1=' + tm1 +'&tm2=' + tm2 +'&tm3=' + tm3 +'&lat=' + center.lat() + '&lng=' +center.lng() + '&radius=' + radius;
	 }else
	 if (tm == "3") {
		var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&lat=21.5433333&lng=39.17277779999995&radius=16';
	 } else {
		 if (tm == '2'){
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&tm1=' + tm1 +'&tm2=' + tm2 +'&tm3=' + tm3 + '&country=' + country +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;		
		 } else {
			var searchUrl = '<?php echo Mage::getBaseUrl();?>storelocator/map2/index?tm=' + tm +'&sort=' + sort +'&tm1=' + tm1 +'&tm2=' + tm2 +'&tm3=' + tm3 +'&lat=' + center.lat() + '&lng=' + center.lng() + '&radius=' + radius;
		 }
	 }
     downloadUrl(searchUrl, function(data) {
       var xml = parseXml(data);
       var markerNodes = xml.documentElement.getElementsByTagName("marker");
       var bounds = new google.maps.LatLngBounds();
       for (var i = 0; i < markerNodes.length; i++) {
         var name = markerNodes[i].getAttribute("name");
         var tipologia = markerNodes[i].getAttribute("tipologia");
         var website = markerNodes[i].getAttribute("website_url");
         var phone = markerNodes[i].getAttribute("phone");
         var address = markerNodes[i].getAttribute("address");	 
         var distance = parseFloat(markerNodes[i].getAttribute("distance"));
		 var moreinfo = markerNodes[i].getAttribute("moreinfo");
		 var flagship = markerNodes[i].getAttribute("notes");
		 var image1 = markerNodes[i].getAttribute("image1");
		 var image2 = markerNodes[i].getAttribute("image2");
		 var image3 = markerNodes[i].getAttribute("image3");
		 var image4 = markerNodes[i].getAttribute("image4");
         var latlng = new google.maps.LatLng(
              parseFloat(markerNodes[i].getAttribute("lat")),
              parseFloat(markerNodes[i].getAttribute("lng")));
		
		var mydistance = markerNodes[i].getAttribute("mydistance");
		var icon=i+1;
		
         createOption(name, distance, i);		 var page='1';
         createMarker(latlng, name, address, moreinfo,website,phone,mydistance,icon,image1,image2,image3,image4,flagship,page,tipologia);
         bounds.extend(latlng);
       }
       map.fitBounds(bounds);
	   if (side_bar_html == "") {
	   document.getElementById("side_bar").innerHTML = '<strong>No Matches Found</strong>';}
	   else {
	   document.getElementById("side_bar").innerHTML = '<div class="heading clearfix animated unselectable hidden" style=" ">Stores<div class="hide"><div class="icon black" style=" "></div><div class="icon grey" style="display:none"></div></div></div><ul class="content">' + side_bar_html + '</ul><div class="button-loadmore"><div id="loadMore-map" class="showmore highlighted btn-search"><?php echo $this->__("CARICA ALTRO"); ?></div></div>';Showmore();}
      });
		
    }
  
    function createMarker(latlng, name, address, moreinfo,website,phone,mydistance,icon,image1,image2,image3,image4,flagship,page,tipologia) {
	if(address !='')
	{
      // var html = "<b>" + name + "</b> <br/>" + address + "<br/>" + moreinfo;
       var html = '<div class="map-detail">';
	html = html + '<div class="grid-full name-map"><div class="grid12-3"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image1+'" /></div><div class="grid12-9"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image2+'" /></div><div class="text-address">flagshipstore<br/>'+ name +'</div></div>';
	html = html + '<div class="clear"></div><div class="map-detail-content"><div class="grid-full">';
	html = html + '<div class="grid12-4 address-map"><div>'+ name +'<div>' + address + '</div><div>'+'T: ' + phone + '</div></div><div class="right"></div></div>';
	html = html + '<div class="grid12-4"><p>'+moreinfo+'</p></div>';
	html = html + '<div class="grid12-4"><p>'+moreinfo+'</p></div>';
	html = html + '</div><div class="clear"></div></div>';
	html = html + '<div class="grid-full buy-map"><div class="grid12-6"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image3+'" /></div><div class="grid12-6"><img alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>'+image4+'" /></div></div>';
	  var cleanaddy = address.replace(/<\/?[^>]+(>|$)/g, "");
	  var shadow = new google.maps.MarkerImage('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/ultimo/default/md/storelocator/bg_br.png' ?>', new google.maps.Size(0, 0) );	   
	  
      var marker = new google.maps.Marker({
        map: map,
		shadow: shadow,
        position: latlng
      });		if(page !='1'){			jQuery('#detail').show();			jQuery('#detail').html(html);			jQuery('#content').hide();			jQuery('#search-left').hide();			jQuery('#side_bar').hide();		}
	  
	   
     cus_km=parseFloat(mydistance); 
	  text_km='';
	  if(cus_km<=10){
		text_km="green";
	  }else if(cus_km> 10 && cus_km<=25){
		text_km="purple";
	  }else{
		text_km="orange";
	  }
	  
	  text_telephone = "";
	  if(phone!=""){
		  text_telephone = '<div class="phone"><a href="tel:'+phone+'">Tel. '+phone+'</a></div>';
	  }
	  
	  
	  text_tipologia = "";
	  if(tipologia.toLowerCase()=="scarpe-borse"){
		  text_tipologia = '<p class="tipologia-scarpe"><?php echo $this->__('Rivenditore Scarpe e Borse'); ?></p>';
	  }else if(tipologia.toLowerCase()=="scarpe-borse-bracciali"){
		  text_tipologia = '<p class="tipologia-borse"><?php echo $this->__('Rivenditore Scarpe, Borse e Bracciali'); ?></p>';
	  }else if(tipologia.toLowerCase()=="bracciali"){
		  text_tipologia = '<p class="tipologia-bracciali"><?php echo $this->__('Rivenditore solo bracciali'); ?></p>';
	  }
		if(website.indexOf('@') >= 0) {
		   html_website = '<a class="website" href="mailto:'+website+'" >'+website+'</a>';
		}else{
			html_website = '<a class="website" href="'+website+'" target="_blank">'+website+'</a>';
		}
	 var image='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=de2666,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	 var image2='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=333333,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	 
	 var  html_popup = "";
		html_popup = '<div class="popup-content"><div class="store_item_content"><div class="whiteLine"></div><div class="marker"><div class="list-marker performance" style="background: url('+image2+') no-repeat" ></div></div><div class="text"><h2>' + name + '</h2><p>'+ address +'</p>'+text_telephone+'<p>'+html_website+'</p><div class="tagList"></div><div class="dottedLine"></div></div><div class="clear"></div><p class="color-km '+text_km+'" style="display:none">'+ mydistance +' km'+'</p>'+text_tipologia+'</div></div>';

	  google.maps.event.addListener(marker, 'click', function() {
		  infoWindow.setContent(html_popup);
		  infoWindow.open(map, marker);
      });
	  
	  
	  setAllMap(map);
      markers.push(marker);
	  
	 
	  // if(icon>25){
	  // var image='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=333333,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	  // var image2='http://chart.apis.google.com/chart?cht=it&chs=32x32&chco=CC0000,000000ff,ffffff01&chl='+icon+'&chx=CCCCCC,12&chf=bg,s,00000000&ext=.png';
	  // }
	  
	
	  
	  marker.setIcon(image);
	  if(flagship != 2)
	  {
		side_bar_html += '<li class="store_item"  ><div class="store_item_content"><div class="whiteLine"></div><div class="marker"><div class="list-marker performance" style="background: url('+image2+') no-repeat" ></div></div><div class="text"><a href="javascript:myclick(' + (markers.length-1) + ')"><h2>' + name + '</h2></a><p>'+ address +'</p>'+text_telephone+'<p>'+html_website+'</p><div class="tagList"></div><div class="dottedLine"></div></div><div class="clear"></div><p class="color-km '+text_km+'" style="display:none">'+ mydistance +' km'+'</p>'+text_tipologia+'</div></li>';
		} else {
		side_bar_html += '<li class="store_item no-flagship-color" href="#contact-popup"><div class="store_item_content"><div class="whiteLine"></div><div class="marker"><div class="list-marker performance" style="background: url('+image2+') no-repeat" ></div></div><div class="text"><a href="javascript:myclick(' + (markers.length-1) + ')"><h2>' + name + '</h2></a><p>'+ address +'</p>'+text_telephone+'<p>'+html_website+'</p><div class="tagList"></div><div class="dottedLine"></div></div><div class="clear"></div><p class="color-km '+text_km+'" style="display:none">'+ mydistance +' Km'+'</p>'+text_tipologia+'</div></li>';
		}
		
		
		
	}
    }
function setAllMap(map) {
   for (var i = 0; i < markers.length; i++) {
      markers[i].setMap(map);
   }
   
}
function myclick(i,flagship) {
	google.maps.event.trigger(markers[i], "click");
	var top = jQuery('.page_navigation').position().top;
	jQuery("html, body").animate({scrollTop: top}, 1000);
}
    function createOption(name, distance, num) {
      var option = document.createElement("option");
      option.value = num;
      option.innerHTML = name + "(" + distance.toFixed(1) + ")";
      locationSelect.appendChild(option);
    }
    function downloadUrl(url, callback) {
      var request = window.ActiveXObject ?
          new ActiveXObject('Microsoft.XMLHTTP') :
          new XMLHttpRequest;
      request.onreadystatechange = function() {
        if (request.readyState == 4) {
          request.onreadystatechange = doNothing;
          callback(request.responseText, request.status);
        }
      };
      request.open('GET', url, true);
      request.send(null);
	 
    }
    function parseXml(str) {
      if (window.ActiveXObject) {
        var doc = new ActiveXObject('Microsoft.XMLDOM');
        doc.loadXML(str);
        return doc;
      } else if (window.DOMParser) {
        return (new DOMParser).parseFromString(str, 'text/xml');
      }
    }
    function doNothing() {}
    //Nothing here>
	function changetab(tm,tm2){
		jQuery('.tabstyle').attr('style','');
		jQuery('#' + tm2).attr('style','background: #fff;border-right: 1px solid #E5E5E5;border-left: 1px solid #E5E5E5');
		jQuery('#tab1content').addClass('hidencontenttab');
		jQuery('#tab2content').addClass('hidencontenttab');
		jQuery('#' + tm).removeClass('hidencontenttab');
		jQuery('#' + tm).show();
	}
	function changecity(tm){
		if (jQuery('#city').val() == "0"){
			searchLocations(3);
		} else {
			searchLocations(tm);
			
			
		}	
	}
			
		
	
	
	 function changevalue(e)
	 {
		jQuery('#addressInput').val(e);
		jQuery('#result_search').hide();
		 fillterLocations(2,1,2,3);
	 }
	 function search()
	 {	
		fillterLocations(2,1,2,3);
		jQuery('#content').show();
		jQuery('#side_bar').show();
		jQuery('#back').show();
		jQuery('#detail').hide();
		jQuery('#city').show();
		
	 }
	 jQuery( document ).ready(function( $ ) {
		jQuery('#addressInput').keyup(function(e) {
			if(e.keyCode == 13) {
				fillterLocations(2,1,2,3);
				jQuery('#content').show();
				jQuery('#side_bar').show();
				jQuery('#back').show();
				jQuery('#detail').hide();
				jQuery('#city').show();
			}
		});
	})
	 
	 function changesort()
	 {
		 fillterLocations(2,1,2,3);
	 }
	
	function backurl()
	 {
		parent.history.back();
        return false;
	 }
	
	function clearLocations() {
     // infoWindow.close();
     for (var i = 0; i < markers.length; i++) {
       markers[i].setMap(null);
     }
     markers.length = 0;
	side_bar_html = "";
   }
   
   function Showmore(){
	   size_li = jQuery(".store_item").size();
		x=12;
		jQuery('#side_bar .content li:lt('+x+')').show();
		jQuery('#loadMore-map').click(function () {
			x= (x+12 <= size_li) ? x+12 : size_li;
			jQuery('#side_bar .content li:lt('+x+')').show();
			 
			if(x >= size_li){
				jQuery('#loadMore-map').hide();
			}
		});
   }
   
   
  </script>
<body style="margin:0px; padding:0px;" onLoad="load()" class="storelocator">

<div class="contact-content">
	<div class="container"><div class="negozi-title"><h1><?php echo $this->__('Storelocator') ?></h1></div></div>
  <div class="storewrap">
		<div class="container">
			<div id="detail"></div>	
			<div id="headerContainer">
				<div class="location-search">
				<div id="search-left">
					<div class="page-title">
						<h1><?php echo $this->__('Seleziona città') ?></h1>
					</div>
					<div class="head-left">
						
						<div id="search-left" class="search-left">
							<div class="test-search">
								<?php if (Mage::getSingleton('core/session')->getSearchvalue()!= "") { ?>
								<input placeholder="Inserisci la città" type="text" value="<?php echo Mage::getSingleton('core/session')->getSearchvalue() ?>" id="addressInput"  size="30" />
								<?php } else { ?>
								<input placeholder="Inserisci la città" type="text" id="addressInput"  size="30" />
								
								<?php } ?>
								<div class="searchButton unselectable">
									<div class="normal"></div>
									<div class="highlighted btn-search" onClick="search()" style="display: block;">Cerca</div>
								</div>
								
								<div id="content_progress" style="float:left"></div>
								<div class="clear"></div>
							</div>
							
						</div>
						<?php /* <div class="lt">
							<span onClick="my_address()" style="cursor: pointer" class="anc_arrow" id="geolocationButton"><?php echo $this->__('determina la tua posizione') ?></span>
						</div> */ ?>
				<script>
				function my_address()
				{
					if (navigator.geolocation) {
					  navigator.geolocation.getCurrentPosition(mia_posizione);
					}else{
					  alert('La geo-localizzazione NON è possibile');
					}
				}

				function mia_posizione(position) {
				  var lat = position.coords.latitude;
				  var lon = position.coords.longitude;
				  var latlng = new google.maps.LatLng(lat,lon);
				  var geocoder = new google.maps.Geocoder();
				  geocoder.geocode({'latLng':latlng},function(data,status){
					if(status == google.maps.GeocoderStatus.OK){
						var add = data[1].formatted_address;
						jQuery('#addressInput').val(add);
						}
				  
				  })  
				}
				  
				</script>
					</div>
				
				<div class="collect-map">
					<a href="#"><div id="back" onClick="searchLocations(2)"   ><h4>back</h4></div></a>
				</div>
				<div>
				
				
				
			<div id="finter" class="search-bottom hidden" style="padding-top:20px;" >				
			</div>
			<div class="clear"></div>
			
			
			<div class="clear"></div>
			</div>			
			<div style="display:none"><select id="locationSelect" style="width:100%;visibility:hidden"></select></div>
			</div>
			
		
	</div>
	<div id="content">
				<div class="content-map">
					<div id="side_bar"></div>
					<div class="page_navigation"></div>	
					<div class="info_text"></div>
				</div>
				
			</div>	
	</div>
	</div>
			<div class="clear"></div>
			<table border="0" bordercolor="" style="position: relative;z-index: 1;" width="100%" cellpadding="0" cellspacing="0">
			<tr>								
				
				<td class="map">		  
					<div id="map" style="width:100%;height:400px;"></div>					
				</td>
			</tr>
		</table>
			
			
	</div>
	<script> searchLocations(2);
</script>
<div style="display:none;">
	<div id="contact-popup">
		<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('contacts/form2.phtml')->toHtml() ?>
	</div>
</div>
</div>
<script>
	// jQuery(document).ready(function(){
		// jQuery(".popup-contact").colorbox({inline:true, width:"50%"});
	// });
	function showpopup(email,name){
		jQuery('#id_email_retailer').val(email);
		jQuery('#id_name_retailer').val(name);
		jQuery.colorbox({inline:true, width:"50%", open:true, href:"#contact-popup",
            onClosed: function() {
                 jQuery('#contact-popup').hide();
            },
            onOpen: function() {
                 jQuery('#contact-popup').show();
            }
           }); 
	}
</script>

	<style>
		.page_navigation , .alt_page_navigation{
			padding-bottom: 10px;
		}
		.page_navigation a, .alt_page_navigation a{
			padding:3px 10px;
			margin:2px;
			color:white;
			text-decoration:none;
			float: left;
			font-family: Tahoma;
			font-size: 12px;
			background-color:#dddddd;
		}
		.active_page{
			background-color:white !important;
			color:black !important;
		}
		.map img {
			max-width: none!important;
		}
		
		.tabstyle { color: #999999;cursor: pointer;float: left;font-family: CustomAdiHausPSBold,arial,helvetica,sans-serif;font-size: 12px;font-weight: normal;line-height: 100%;padding: 22px 20px 15px;text-align: left;text-decoration: none;text-transform: uppercase;vertical-align: middle;}
		.content_info { height: 105px;overflow: auto; }
		.gm-style > div > div > div > div > div,.gm-style > div > div > div > div > div > div > div {border: none !important}
		.gm-style-iw, .gm-style-iw > div {     overflow-x: hidden !important;overflow-y: auto !important;}
		.hidencontenttab { display:none !important}
		#city {height: 50px;padding: 16px 10px;width: 106px;}
		.tabcontent p { font-size: 14px; margin-bottom: 1px; margin-top: 0 !important; text-transform: none; }
		.storewrap img {max-width: none;}
		.footer-medical-division { margin-top:30px; color:#354389; font-size:12px; display: flex; text-align:center; align-items:center; padding-bottom: 20px; padding-top: 20px; border-top: solid 1px #efefef;}
        .footer-medical-division img { padding-top: 15px; vertical-align:bottom; }
        .disp_medico { margin: 0 auto; max-width: 314px; text-align: left; }
        @media (max-width: 991px) {
            .footer-medical-division { display: inline; padding-bottom: 8px; border-top: solid 1px #efefef;}   
            .disp_medico { text-align: center; }
        }
		
		#side_bar .store_item {
			display: none;
		}
		#loadMore-map.showmore {
			background-color: #fff;
			border: 1px solid;
			cursor: pointer;
			font-size: 14px;
			line-height: 40px;
			text-align: center;
			width: 145px;
		}
		#loadMore-map.showmore {
			background-color: #fff;
			border: 1px solid;
			cursor: pointer;
			display: inline-block;
			font-size: 14px;
			line-height: 40px;
			text-align: center;
			width: 145px;
		}
		.button-loadmore{
			text-align: center;
		}
		.tipologia-scarpe, .tipologia-bracciali, .tipologia-borse {
			font-size: 14px;
			padding-top: 15px;
			text-transform: uppercase;
		}
		.tipologia-bracciali {
			color: #37c064;
		}
		.tipologia-scarpe {
			color: #f5a046;
		}
			.tipologia-borse {
			color: #FF00FF;
		}
		.store_item_content .website {
		    text-transform:uppercase;
		}
	</style>
</body>