<!-- List all categories and their second level subcategories -->
<div class="block block-list block-categories">
    <div id="block-categories" class="block-title active">
        <strong><span><?php echo $this->__('Categories'); ?></span></strong>
    </div>

<div id="leftnav" class="block-content" style="display:block">
    <?php $helper = $this->helper('catalog/category') ?>
    <?php $categories = $this->getStoreCategories() ?>
    <?php if (count($categories) > 0): ?>
        <ul id="leftnav-tree" class="level0">
            <?php foreach($categories as $category): ?>
                <li class="level0<?php if ($this->isCategoryActive($category)): ?> active<?php endif; ?>">
				<?php $subcategories = $category->getChildren() ?>
                    <a class="<?php if($subcategories->count()) : ?>perent<?php endif; ?>" href="<?php echo $helper->getCategoryUrl($category) ?>"><span><?php echo $this->escapeHtml($category->getName()) ?></span></a>
                    <?php //if ($this->isCategoryActive($category)): ?>
                        
                        <?php if($subcategories->count()) : ?>
							
						 <?php if($subcategories->count()) : ?>
							<div class="toggle-title level0 fa fa-plus-circle"></div>
						<?php endif; ?>
                            <ul id="leftnav-tree-<?php echo $category->getId() ?>" class="level1 toggle-menuleft">
                                <?php foreach($subcategories as $subcategory): ?>
                                    <li class="level1<?php if ($this->isCategoryActive($subcategory)): ?> active<?php endif; ?>">
										 <?php $secondLevelSubcategories = $subcategory->getChildren() ?>
                                        <a class="<?php if($secondLevelSubcategories->count()) : ?>perent<?php endif; ?>" href="<?php echo $helper->getCategoryUrl($subcategory) ?>"><?php echo $this->escapeHtml(trim($subcategory->getName(), '- ')) ?></a>
                                        
										 <?php if($secondLevelSubcategories->count()) : ?>
												<div class="toggle-title level1 fa fa-plus-circle"></div>
											<?php endif; ?>
                                         <?php if (count($secondLevelSubcategories ) > 0): ?>
											<ul id="leftnav-tree-<?php echo $subcategory->getId() ?>" class="level2 toggle-menuleft">
												<?php foreach($secondLevelSubcategories as $secondLevelSubcategory ): ?>
													<li class="level2<?php if ($this->isCategoryActive($secondLevelSubcategory )): ?> active<?php endif; ?>">
														<a href="<?php echo $helper->getCategoryUrl($secondLevelSubcategory ) ?>"><?php echo $this->escapeHtml(trim($secondLevelSubcategory ->getName(), '- ')) ?></a>
													</li>
													<?php endforeach; ?>
											</ul>
                        <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php //endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateList('leftnav-tree', 'recursive')</script>
    <?php endif; ?>
</div>
</div>


<script>
	jQuery('.toggle-menuleft').hide();
	 jQuery(function() {
		if(jQuery('#leftnav-tree li.level0').hasClass('active')){
			jQuery('#leftnav-tree li.level0.active').find('.toggle-title.level0.fa').removeClass('fa-plus-circle').addClass('fa-minus-circle');
			jQuery('#leftnav-tree li.level0.active').find('.toggle-menuleft.level1').show();
		}
		 if(jQuery('#leftnav-tree li.level1').hasClass('active')){
			jQuery('#leftnav-tree li.level1.active').find('.level1.toggle-title.fa').removeClass('fa-plus-circle').addClass('fa-minus-circle');
			jQuery('#leftnav-tree li.level1.active').find('.toggle-menuleft.level2').show();
		}
		
		jQuery(".toggle-title").click(function(event){
			var  test = jQuery('.toggle-title .fa');
			if(jQuery(this).hasClass('fa-plus-circle')) {       
				jQuery(this).removeClass('fa-plus-circle').addClass('fa-minus-circle');
			}
			else{
				jQuery(this).removeClass('fa-minus-circle').addClass('fa-plus-circle');
			}
			event.preventDefault();
			jQuery(this).toggleClass('active');
			jQuery(this).next('.toggle-menuleft').slideToggle();
		  });
		
	});
</script>