<?php
$items = $this->getLocation();
$OptionCountry = $this->getCountry();
$lat=$_POST['lat'];
$lng=$_POST['lng'];
$countr=$_POST['country'];
$distan=array();
foreach($OptionCountry as $code => $name)
{
	$coords = getCoordinates($name);
		$x1=$lat;
		$y1=$lng;
		$x2=$coords[0];
		$y2=$coords[1];
		$earthRadius = 6371;
		$latFrom = deg2rad($x1);
		$lonFrom = deg2rad($y1);
		$latTo = deg2rad($x2);
		$lonTo = deg2rad($y2);

		$latDelta = $latTo - $latFrom;
		$lonDelta = $lonTo - $lonFrom;
		$angle = 2 * asin(sqrt(pow(sin($latDelta / 2), 2) + cos($latFrom) * cos($latTo) * pow(sin($lonDelta / 2), 2)));
	$dist=$angle * $earthRadius;	
	$distan[]=$angle * $earthRadius;	
	$array[]=array ('distan' => $dist, 'code' => $code, 'name' => $name);
}
 $distance=min($distan);
if($lat==0 && $lng==0){
?>
	<select id="city" onchange="changecity(1)">						
		<option  value=""></option>
	</select>
<?php
}
else if ($lat !=0 && $lng !=0 && $countr != ''){
?>
	<select id="city" onchange="changecity(1)">						
		<option  value="<?php echo $countr ?>"><?php echo $countr ?></option>
	</select>
<?php
}
else if($lat !=0 && $lng !=0 && $countr == ''){
?>
	<?php foreach($array as $arr)
		{
			if($arr['distan']==$distance)
			{
	?>
				<select id="city">						
					<option  value="<?php echo $arr['code'] ?>"><?php echo $arr['name'] ?></option>
				</select>
	<?php			
			}
		}
	?>
<?php
}
function getCoordinates($address){
    $address = urlencode($address);
    $url = "http://maps.google.com/maps/api/geocode/json?sensor=false&address=" . $address;
    $response = file_get_contents($url);
    $json = json_decode($response,true);
    $lat = $json['results'][0]['geometry']['location']['lat'];
    $lng = $json['results'][0]['geometry']['location']['lng']; 
    return array($lat, $lng);
}
?>